# Generated by Django 5.1.4 on 2025-01-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
    ]
