# Generated by Django 5.1.4 on 2025-01-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_product_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='etat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
