# Generated by Django 5.1.4 on 2024-12-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_phone_verified',
            new_name='is_email_verified',
        ),
    ]
