# Generated by Django 5.1.4 on 2024-12-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_rename_is_phone_verified_userprofile_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
