# Generated by Django 5.1.4 on 2024-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isSendMailChacked',
            field=models.BooleanField(default=False),
        ),
    ]
