# Generated by Django 5.1.4 on 2024-12-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_userprofile_issendmailchacked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isPrivacyChecked',
            field=models.BooleanField(default=False),
        ),
    ]
