# Generated by Django 5.1.4 on 2024-12-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_usergoogle_address_usergoogle_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoogle',
            name='avatar',
        ),
        migrations.AddField(
            model_name='usergoogle',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
