# Generated by Django 5.1.4 on 2024-12-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_remove_usergoogle_avatar_usergoogle_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoogle',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='usergoogle',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
