# Generated by Django 5.1.4 on 2024-12-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_remove_usergoogle_avatar_url_usergoogle_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoogle',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usergoogle',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usergoogle',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
