# Generated by Django 5.1.4 on 2025-01-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_remove_usergoogle_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='story',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='story_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
