# Generated by Django 5.1.4 on 2025-01-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_userprofile_story_userprofile_story_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='story',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='story_created_at',
        ),
    ]
