# Generated by Django 5.1.4 on 2025-01-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0022_rename_identifier_adminuser_indetifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='indetifier',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
