# Generated by Django 5.1.4 on 2025-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0025_rename_indetifier_adminuser_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfacebook',
            name='hasStory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergoogle',
            name='hasStory',
            field=models.BooleanField(default=False),
        ),
    ]
